"""empty message

Revision ID: 861c7b067252
Revises: 8bcfbb5d4c32
Create Date: 2026-04-20 18:53:03.625740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '861c7b067252'
down_revision: Union[str, Sequence[str], None] = '8bcfbb5d4c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('antepassado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Minha Família'"), nullable=False))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_civil', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Solteiro(a)'"), nullable=False))
        batch_op.add_column(sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Masculino'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('sexo')
        batch_op.drop_column('estado_civil')

    with op.batch_alter_table('antepassado', schema=None) as batch_op:
        batch_op.drop_column('familia')

    # ### end Alembic commands ###
