"""empty message

Revision ID: 9e16477e48f6
Revises: 861c7b067252
Create Date: 2026-04-20 19:07:29.998848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9e16477e48f6'
down_revision: Union[str, Sequence[str], None] = '861c7b067252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###
