"""empty message

Revision ID: efbb96f55fe7
Revises: 
Create Date: 2026-03-25 20:03:07.959378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'efbb96f55fe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antepassado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vinculo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linhagem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('antepassado')
    # ### end Alembic commands ###
