"""empty message

Revision ID: efcecc25a648
Revises: 9e16477e48f6
Create Date: 2026-04-20 19:24:16.633155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'efcecc25a648'
down_revision: Union[str, Sequence[str], None] = '9e16477e48f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('aceitou_termos', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('aceitou_termos')
        batch_op.drop_column('nome_completo')

    # ### end Alembic commands ###
